kind: pipeline
name: default

steps:

- name: install
  image: node
  commands:
  - npm install

- name: test
  image: node
  commands:
  - npm test

- name: build
  image: node
  commands:
  - npm run build
  volumes:
  - name: cache
    path: /drone/src/build

- name: npm
  image: plugins/npm
  settings:
    username: arwed
    token:
      from_secret: npm_token
    email: arwed.mett@googlemail.com
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  volumes:
  - name: cache
    path: /drone/src/build

volumes:
- name: cache
  temp: {}
