kind: pipeline
name: default

steps:

- name: install
  image: node
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
  - npm install

- name: test
  image: node
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
  - npm test

- name: build
  image: node
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
  - npm run build

- name: publish
  image: node
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
    - if [ "$(npm view @arwed/sanitize dist-tags.latest)" = "$(node -p -e "require('./package.json').version")" ]; then echo not publishing; else npm whoami & npm publish; fi
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
